### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by opkiler22789** [Muqsit/ChestShop#1]
`[15:53:54] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\item\Item::setNamedTag() must be an instance of pocketmine\nbt\tag\CompoundTag, boolean given, called in /root/plugins/ChestShop-master/src/ChestShop/Main.php on line 122" (EXCEPTION) in "/src/pocketmine/item/Item" at line 774`

**Comment by Muqsit** [comment]
The plugin is still WIP.

**Comment by Muqsit** [comment]
Try the phar I posted here:
https://forums.pmmp.io/posts/9799/
