### ISSUE TITLE
Selling Items?

### ISSUE THREAD

**Issue by SinlesFlyer376** [Muqsit/ChestShop#10]
Could I use this same code to sell items instead of Buying or could you add that? That would be cool

**Comment by Muqsit** [comment]
I could but it isn't a common thing for now.
That might even have to be another plugin since this is ChestShop and not ChestSell.
Why do you need such a feature tho?

**Comment by SinlesFlyer376** [comment]
I think it would be great to have and if I make a Prison server which I am they can do /cs and Sell when they click the item they are selling. I think it would be a great feature for Prison Servers
