### ISSUE TITLE
Error during use shop

### ISSUE THREAD

**Issue by valentin-tetushkin** [Muqsit/ChestShop#108]
When I use the shop, with some probability a black screen may appear, which is fixed only by rejoin the server

**Comment by Muqsit** [comment]
Yeah it's a bug with the client. Have [InvCrashFix](https://github.com/Muqsit/InvCrashFix) downloaded on your server, it'll fix the screen issues with guis.

**Comment by valentin-tetushkin** [comment]
Thanks

**Comment by TukangM** [comment]
> Yeah it's a bug with the client. Have [InvCrashFix](https://github.com/Muqsit/InvCrashFix) downloaded on your server, it'll fix the screen issues with guis.

solved :D
