### ISSUE TITLE
Object names appear in another language

### ISSUE THREAD

**Issue by MrBlasyMSK** [Muqsit/ChestShop#110]
![image](https://user-images.githubusercontent.com/85447029/160496565-398095b7-f443-432c-99de-0e97f6b26e44.png)
![image](https://user-images.githubusercontent.com/85447029/160496579-b3d66825-ca6c-4b8f-9e9e-53e2957788b2.png)

**Comment by Muqsit** [comment]
This isn't something caused by ChestShop, check your minecraft language settings.
