### ISSUE TITLE
bug chest shop UI gone 

### ISSUE THREAD

**Issue by TukangM** [Muqsit/ChestShop#114]
[﻿[url=https://youtube.com/shorts/JuojI_RtMnc]Youtube[/url]](https://youtube.com/shorts/JuojI_RtMnc?feature=share)
Hopefully in the next update it can be fixed

**Comment by Muqsit** [comment]
This is probably related to #108. Can you try the steps mentioned here and see if that resolves the issue: https://github.com/Muqsit/ChestShop/issues/108#issuecomment-1069449247
