### ISSUE TITLE
Error by 1.18.30

### ISSUE THREAD

**Issue by Wayder228** [Muqsit/ChestShop#116]
Please update to 1.18.30, the plugin crashes on startup!

**Comment by Muqsit** [comment]
Can you send the error message here

**Comment by Wayder228** [comment]
> Можете ли вы отправить сообщение об ошибке здесь

Okay, I'll find it right now!

**Comment by Wayder228** [comment]
> Может ли вы отправить сообщение по этому поводу

this error when starting the server.

**Comment by Wayder228** [comment]
> Может ли вы отправить сообщение по этому поводу

this error when starting the server.

**Comment by Muqsit** [comment]
Seems to work fine on latest PocketMine version.

**Comment by Wayder228** [comment]
> Кажется, работает нормально на последней версии PocketMine. Я предлагаю повторно загрузить файл PocketMine .phar.

I have a kernel for a multi version (pull request), could you help me how to fix this? ask!

**Comment by Wayder228** [comment]
> Кажется, работает нормально на последней версии PocketMine. Я предлагаю повторно загрузить файл PocketMine .phar.

Everything works well on this kernel, but only this error :(
