### ISSUE TITLE
getTargetItem

### ISSUE THREAD

**Issue by XFizzer** [Muqsit/ChestShop#12]
I keep getting this issue every time I try to put something into my inventory

17.02 19:08:34 [Server] Server thread/CRITICAL Error: "Call to a member function getTargetItem() on null" (EXCEPTION) in "/ChestShop.phar/src/ChestShop/EventListener" at line 81
17.02 19:08:34 [Server] Server thread/CRITICAL "Could not pass event 'pocketmine\event\inventory\InventoryTransactionEvent' to 'ChestShop v2': Call to a member function getTargetItem() on null on ChestShop\EventListener

**Comment by Muqsit** [comment]
Use PMMP, NO forks or spoons.
