### ISSUE TITLE
Error: breaks the interface

### ISSUE THREAD

**Issue by Diedman9T** [Muqsit/ChestShop#120]
When I try to buy something, my interface (inventory and chat) breaks. Problem can be solved by rejoining server... But it's uncomfortable.

**Comment by Muqsit** [comment]
Does the problem still occur with this build: [ChestShop_dev-65.phar](https://poggit.pmmp.io/r/174840/ChestShop_dev-65.phar)

**Comment by TukangM** [comment]
https://poggit.pmmp.io/ci/Muqsit/InvCrashFix/~ maybe?
