### ISSUE TITLE
Other world chest don't work.

### ISSUE THREAD

**Issue by AndriassY** [Muqsit/ChestShop#16]
The plugin gave problem to put or pick up items on normal chests... Because in the plugin it says

Set on null.

**Comment by Muqsit** [comment]
Closing due to minimal information.

**Comment by corytortoise** [comment]
I believe the issue is that he can't transfer items between normal chests because of the plugin.
https://forums.pmmp.io/threads/per-world-plugin.1431/#post-16011

**Comment by AndriassY** [comment]
I've already do another issua with more info  :)
