### ISSUE TITLE
createTile()

### ISSUE THREAD

**Issue by XFizzer** [Muqsit/ChestShop#17]
13.03 07:07:21 [Server] Server thread/CRITICAL TypeError: "Argument 2 passed to pocketmine\tile\Tile::createTile() must be an instance of pocketmine\level\Level, instance of pocketmine\level\format\Chunk given, called in phar:///plugins/ChestShop.phar/src/ChestShop/Main.php on line 109" (EXCEPTION) in "/src/pocketmine/tile/Tile" at line 85
13.03 07:07:21 [Server] Server thread/CRITICAL Unhandled exception executing command 'cshop' in chestshop: Argument 2 passed to pocketmine\tile\Tile::createTile() must be an instance of pocketmine\level\Level, instance of pocketmine\level\format\Chunk given, called in phar:///plugins/ChestShop.phar/src/ChestShop/Main.php on line 109

And yes I'm on pocketmine

**Comment by Muqsit** [comment]
Update pocketmine.

**Comment by XFizzer** [comment]
I have the latest pocketmine version

**Comment by Muqsit** [comment]
You don't. The latest pocketmine listens to level instead of chunks before spawning tile entities.

**Comment by XFizzer** [comment]
Right and if you use $player->level instead of $player->chuck its works fine
