### ISSUE TITLE
Various Bugs on plug,

### ISSUE THREAD

**Issue by AndriassY** [Muqsit/ChestShop#18]
Used this plugin for some weeks... This is really awesome but... I've looked for some bugs:

1. Normal chests (block) don't work (chestshop plugin doesn't permise this) ... I can't put or pick up item from normal chests... 

2. When i try to buy some items on it, and i haven't money... It stop raklib interface and crashed... (always)

Errors:
1. could not pass event: Pocketmine/event/inventory/inventorytransictionevent Call to a member function getTargetItem on chestshop event listener.

2. Trying to get property of non-object in... Customchest.php line 38 --- function getValue() on null Stopped raklib interface

**Comment by SinlesFlyer376** [comment]
It just won't let me buy the item in the chest and only says Stone on it

**Comment by Muqsit** [comment]
Use pure pmmp, no forks.

**Comment by daniktheboss** [comment]
Why not make a branch and support it?

**Comment by SuperMaXAleX** [comment]
Cancelled event are horrible on forks, and actually, pmmp is now the only pure software. Tesseract, Elywing and Genisys have been stopped.
