### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by amon28** [Muqsit/ChestShop#20]
When I load the plug in there's a warning saying this

Warning: yaml_parse_file(/storage/emulated/0/Pocketmine/plugins/ChestShop/shops.yml): failed to open stream: No such file or directory in /storage/emulated/0/Pocketmine/plugins/ChestShop-master/src/ChestShop/Main.php on line 84

**Comment by Muqsit** [comment]
Looks like your user does not have permissions to the plugins directory. Try giving yourself the required privileges.
