### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alair069** [Muqsit/ChestShop#21]
[Tesseract] [9:50 pm] CRITICAL> "Could not pass event 'pocketmine\event\inventory\InventoryTransactionEvent' to 'ChestShop v3': Call to undefined method pocketmine\inventory\BaseTransaction::getSourceItem() on ChestShop\EventListener
[Tesseract] [9:50 pm] CRITICAL> Error: "Call to undefined method pocketmine\inventory\BaseTransaction::getSourceItem()" (EXCEPTION) in "/plugins/ChestShop-master/src/ChestShop/EventListener" at line 86

**Comment by Muqsit** [comment]
Use PMMP. Tesseract sucks.
