### ISSUE TITLE
Hi Muqsit

### ISSUE THREAD

**Issue by NycuRO** [Muqsit/ChestShop#22]
https://images.discordapp.net/.eJwFwdENgyAQANBdGIA7Dk7BBRo_OoMhSNBGC4HrV9Pd-95XffqlFnWItLEA7OdIte96SO2xZF1qLVeO7Rw61RuiSEzHnd8ygIILPDnCgIzOBEKwyNbaeWLDgY0n9LA-HxuhmdGR2Ywlj6xfrajfH5SpJCA.c5usHJwq-Imptmkrijtv_Iljd7k

Hi @Muqsit

**Comment by Muqsit** [comment]
Lol

**Comment by NycuRO** [comment]
:DD :DD @Muqsit
