### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NiclasQueen** [Muqsit/ChestShop#24]
PocketMine-MP Crash Dump Sun May 21 13:13:08 CEST 2017

Error: Call to a member function getItem() on null
File: /src/pocketmine/tile/Chest
Line: 78
Type: notice

Code:
[69] 
[70] 			parent::close();
[71] 		}
[72] 	}
[73] 
[74] 	public function saveNBT(){
[75] 		$this->namedtag->Items = new ListTag("Items", []);
[76] 		$this->namedtag->Items->setTagType(NBT::TAG_Compound);
[77] 		for($index = 0; $index < $this->getSize(); ++$index){
[78] 			$this->setItem($index, $this->inventory->getItem($index));
[79] 		}
[80] 	}
[81] 
[82] 	/**
[83] 	 * @return int
[84] 	 */
[85] 	public function getSize(){
[86] 		return 27;
[87] 	}
[88] 

Backtrace:
#0 /src/pocketmine/level/format/io/region/Anvil(85): pocketmine\tile\Chest->saveNBT(boolean)
#1 /src/pocketmine/level/format/io/region/RegionLoader(178): pocketmine\level\format\io\region\Anvil->nbtSerialize(pocketmine\level\format\Chunk object)
#2 /src/pocketmine/level/format/io/region/McRegion(313): pocketmine\level\format\io\region\RegionLoader->writeChunk(pocketmine\level\format\Chunk object)
#3 /src/pocketmine/level/Level(996): pocketmine\level\format\io\region\McRegion->saveChunk(integer 39, integer 61)
#4 /src/pocketmine/level/Level(984): pocketmine\level\Level->saveChunks(boolean)
#5 /src/pocketmine/Server(2265): pocketmine\level\Level->save(boolean )
#6 /src/pocketmine/Server(2405): pocketmine\Server->doAutoSave(boolean)
#7 /src/pocketmine/Server(2141): pocketmine\Server->tick(boolean)
#8 /src/pocketmine/Server(2023): pocketmine\Server->tickProcessor(boolean)
#9 /src/pocketmine/Server(1642): pocketmine\Server->start(boolean)
#10 /src/pocketmine/PocketMine(492): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/gs/gs/data/servers/4832880/pocketmine.phar/, string /home/gs/gs/data/servers/4832880/, string /home/gs/gs/data/servers/4832880/plugins/)
#11 (1): require_once(string phar:///home/gs/gs/data/servers/4832880/pocketmine.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6.2dev #0 [Protocol 107; API 3.0.0-ALPHA5]
Git commit: 0000000000000000000000000000000000000000
uname -a: x
PHP Version: 7.0.9
Zend version: 3.0.0
OS : Linux, linux

**Comment by Muqsit** [comment]
This had been fixed two updates back 🤙

**Comment by TDMidkwhatisxd** [comment]
I still got it, and I use latest
