### ISSUE TITLE
Please Fix, Would mean the world to me

### ISSUE THREAD

**Issue by SourSmirnoff** [Muqsit/ChestShop#27]
Critical error while using /cs to try to open the chest shop:

**Server thread/CRITICAL TypeError: "Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putBlockPosition() must be of the type integer, float given, called in phar:///pmmp-latest.phar/src/pocketmine/network/mcpe/protocol/UpdateBlockPacket.php on line 60" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 305
10.07 02:55:31 [Server] Server thread/CRITICAL Unhandled exception executing command 'cshop' in chestshop: Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putBlockPosition() must be of the type integer, float given, called in phar:///pmmp-latest.phar/src/pocketmine/network/mcpe/protocol/UpdateBlockPacket.php on line 60**

My server could really use this, it really simplifies the way a shop on a faction server works, i would really appreciate it if this was fixed

**Comment by Muqsit** [comment]
#25
