### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [Muqsit/ChestShop#28]
PocketMine-MP Crash Dump Tue Jul 11 14:21:11 UTC 2017

Error: Call to a member function getItem() on null
File: src/pocketmine/tile/Chest
Line: 80
Type: notice

Code:
[71] 
[72] 			parent::close();
[73] 		}
[74] 	}
[75] 
[76] 	public function saveNBT(){
[77] 		$this->namedtag->Items = new ListTag("Items", []);
[78] 		$this->namedtag->Items->setTagType(NBT::TAG_Compound);
[79] 		for($index = 0; $index < $this->getSize(); ++$index){
[80] 			$this->setItem($index, $this->inventory->getItem($index));
[81] 		}
[82] 	}
[83] 
[84] 	/**
[85] 	 * @return int
[86] 	 */
[87] 	public function getSize(){
[88] 		return 27;
[89] 	}
[90] 

Backtrace:
#0 src/pocketmine/level/format/io/region/Anvil(85): pocketmine\tile\Chest->saveNBT()
#1 src/pocketmine/level/format/io/region/RegionLoader(178): pocketmine\level\format\io\region\Anvil->nbtSerialize(pocketmine\level\format\Chunk object)
#2 src/pocketmine/level/format/io/region/McRegion(317): pocketmine\level\format\io\region\RegionLoader->writeChunk(pocketmine\level\format\Chunk object)
#3 src/pocketmine/level/Level(993): pocketmine\level\format\io\region\McRegion->saveChunk(integer 0, integer -18)
#4 src/pocketmine/level/Level(981): pocketmine\level\Level->saveChunks()
#5 src/pocketmine/Server(2342): pocketmine\level\Level->save(boolean )
#6 src/pocketmine/Server(2485): pocketmine\Server->doAutoSave()
#7 src/pocketmine/Server(2218): pocketmine\Server->tick()
#8 src/pocketmine/Server(2097): pocketmine\Server->tickProcessor()
#9 src/pocketmine/Server(1679): pocketmine\Server->start()
#10 src/pocketmine/PocketMine(514): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///root/PocketMine-MP.phar/, string /root/, string /root/plugins/)
#11 /root/PocketMine-MP.phar(1): require_once(string phar:///root/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6.2dev #0 [Protocol 113; API 3.0.0-ALPHA6]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux change 2.6.32-48-pve #1 SMP Fri Dec 23 10:22:54 CET 2016 x86_64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

**Comment by TDMidkwhatisxd** [comment]
Maybe if someone die and he still do stuff in shop it cause glitch.
Because wen the server crashed I killed ppl in spawn with splash potion ^^

**Comment by TDMidkwhatisxd** [comment]
Ill wait for a fix :)

**Comment by TDMidkwhatisxd** [comment]
Musqit , this chest shop is a awesome idea. Good Job.

**Comment by Muqsit** [comment]
Thanks, try with the latest commit and let me know if the issue still exists.

**Comment by TDMidkwhatisxd** [comment]
i will try :)
