### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [Muqsit/ChestShop#29]
42:01] [Server thread/CRITICAL]: Unhandled exception executing command 'cs' in chestshop: Return value of ChestShop\Chest\CustomChest::getInventory() must be an instance of ChestShop\Chest\CustomChestInventory, null returned
[17:42:01] [Server thread/CRITICAL]: TypeError: "Return value of ChestShop\Chest\CustomChest::getInventory() must be an instance of ChestShop\Chest\CustomChestInventory, null returned" (EXCEPTION) in "ChestShop_v3.phar/src/ChestShop/Chest/CustomChest" at line 42

I get the error wen I had splash potion in hand.

**Comment by TDMidkwhatisxd** [comment]
I use TapToDo, and I used splash potion in hand to click sign, and maybe some glich triggered.

**Comment by Muqsit** [comment]
Have you modified the source?

**Comment by TDMidkwhatisxd** [comment]
Nope.
And there is another glitch, were if you have no money and u still try to buy item, your hotbar is gone, and if u continue to do that for some time, it will get a black screen.

**Comment by opkiler22789** [comment]
@Muqsit  `Error: "Call to undefined method pocketmine\inventory\BaseTransaction::getSourceItem()" (EXCEPTION) in "/plugins/ChestShop-master/src/ChestShop/EventListener" at line 86`

**Comment by Muqsit** [comment]
@opkiler22789 Don't use spoons.

**Comment by opkiler22789** [comment]
@Muqsit Sorry to have worried

**Comment by Muqsit** [comment]
There is no way this can be produced without plugin modifications. Another cause would be interacting with the plugin on onEnable(), considering the plugin hasn't been enabled yet.
