### ISSUE TITLE
Mini Error

### ISSUE THREAD

**Issue by BogdanMakarchuk** [Muqsit/ChestShop#3]
Notice: Trying to get property of non-object in /root/pvp/plugins/ChestShop-master/src/ChestShop/EventListener.php on line 85
[Tesseract] [05:56:25] CRITICAL> "Could not pass event 'pocketmine\event\inventory\InventoryTransactionEvent' to 'ChestShop v1.0.0': Call to a member function getValue() on null on ChestShop\EventListener
[Tesseract] [05:56:25] CRITICAL> Error: "Call to a member function getValue() on null" (EXCEPTION) in "/plugins/ChestShop-master/src/ChestShop/EventListener" at line 85

Core Tesseract)

**Comment by Muqsit** [comment]
Use pmmp.
