### ISSUE TITLE
MASSIVE ERROR

### ISSUE THREAD

**Issue by Swaggpvp** [Muqsit/ChestShop#31]
When a player does /cs To open the GUI and when they take an item it doesn't display price and non op and op people can just take the item and it doesn't take thier money I'm using all Economy API's

**Comment by Muqsit** [comment]
Can you do /version and send me the output

**Comment by Swaggpvp** [comment]
[Server] [01:12:41] [Server thread/INFO]: -----Server information-----
[Server] [01:12:41] [Server thread/INFO]: This server is running GenisysPro-1.1dev LlamaSpit
[Server] [01:12:41] [Server thread/INFO]: PHP version: 7.0.3
[Server] [01:12:41] [Server thread/INFO]: API: 3.0.1
[Server] [01:12:41] [Server thread/INFO]: Target client: Minecraft PE v1.1.0.9,v1.1.0.55,v1.1.1,v1.1.2,1.1.3
[Server] [01:12:41] [Server thread/INFO]: Protocol version: 113
