### ISSUE TITLE
API 3.0.0ALPHA7 

### ISSUE THREAD

**Issue by optimusprime338** [Muqsit/ChestShop#32]
using pmmp latest release
error:-
[Server thread/CRITICAL]: Unhandled exception executing command 'cs' in chestshop: Return value of ChestShop\Chest\CustomChest::getInventory() must be an instance of ChestShop\Chest\CustomChestInventory, null returned

**Comment by Muqsit** [comment]
I'm waiting for pmmp's 1.2 branch's full inventory transaction implementation. Till then, you gotta wait :|

**Comment by Kyokuneko** [comment]
Eyh, this plugin don't work on my server Api6, he is installed but in my plugin list with /plugin in mcpe is red :/
Can you fix it ?
(Sorry for my english, im french xD)

**Comment by Muqsit** [comment]
There is no valid argument to support PocketMine's 1.1 branch, I'll update this in accordance to 1.2
