### ISSUE TITLE
1.2

### ISSUE THREAD

**Issue by QuiverlyRivalry** [Muqsit/ChestShop#34]
Hi, in 1.2 will you be adding like a custom shop ui/
Likea slider to choose how many items and the price this would b great!

**Comment by BlawoHD** [comment]
@Muqsit You update this Plugin for 1.2 and API 3.0.0-ALPHA9?

**Comment by karanpatel567** [comment]
Tbh its pretty easy to update.

**Comment by QuiverlyRivalry** [comment]
I agree with karan..
but because of 1.2 with new uis
you think muqsit can make it UIShop?
like daniks?

**Comment by Muqsit** [comment]
https://github.com/Muqsit/ChestShop/commit/000c26d96c1e2746995c0ead19a57c550e2af23a
