### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by llronaldoll** [Muqsit/ChestShop#38]
[Server thread/CRITICAL]: Não foi possível passar o evento 'pocketmine\event\inventory\InventoryTransactionEvent' para 'ChestShop v3': Call to undefined method pocketmine\inventory\transaction\action\DropItemAction::getInventory() em ChestShop\EventListener
[23:20:07] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\inventory\transaction\action\DropItemAction::getInventory()" (EXCEPTION) in "ChestShop.phar/src/ChestShop/EventListener" at line 76

**Comment by llronaldoll** [comment]
this error happens whenever an item is thrown on the floor!

**Comment by Muqsit** [comment]
Oh I must've forgotten to check for the specific InventoryAction type

**Comment by llronaldoll** [comment]
Yes, this occurs whenever an item is played, or selected in the creative inventory.
