### ISSUE TITLE
Players can take the categories after reload

### ISSUE THREAD

**Issue by Adam1609** [Muqsit/ChestShop#55]
Do the /reload command make players can take whatever item in the categories in ChestShop

**Comment by MSG100TC** [comment]
Same problem

**Comment by Muqsit** [comment]
To be fair, PocketMine plugins are barely /reload-friendly and so I've never given attention to it.

**Comment by Adam1609** [comment]
This is optional bug, I assume :D

**Comment by mikeygio10** [comment]
Don’t reload the server then fixed

**Comment by Muqsit** [comment]
`/reload`s are unrecommended for this very reason (it has been removed in API 4.0 btw). A reload command is better implemented by the plugin author (probably as a `/chestshop reload`).
