### ISSUE TITLE
We can not open categories and players can take the items in /cs

### ISSUE THREAD

**Issue by Matthieu05** [Muqsit/ChestShop#58]
I can make the command to create a category, when I do /cs there is the category but when I click on it, the category does not open. Players can also retrieve the items in the /cs. I am using version 1.4.1 of Minecraft.

**Comment by Muqsit** [comment]
does it happen after you /reload the server?

**Comment by Matthieu05** [comment]
No I did not do /reload

**Comment by Muqsit** [comment]
Can you provide steps to reproduce this? This doesn't seem to happen by vaguely doing what you stated (type `/cs` and tap a category).
Also, are you using the latest .phar file and what's your output for `/version` command?

**Comment by Matthieu05** [comment]
Oops sorry for bothering you, I did not understand that I had to put the item in his inventory to open it, I just had to click on it
