### ISSUE TITLE
[Request] Remove item from a category

### ISSUE THREAD

**Issue by Adam1609** [Muqsit/ChestShop#61]
Can you add the removing from categories function in the plugin, it would be perfect if it has without deleting the categories and start all over again

**Comment by Crypt97** [comment]
I support it! Much has been caused by the lack of it.

**Comment by Muqsit** [comment]
Added `/cs removeitem` in v5.0.0 https://poggit.pmmp.io/ci/Muqsit/ChestShop/ChestShop
