### ISSUE TITLE
Categories disappear after restarting the server.

### ISSUE THREAD

**Issue by Antonio231102** [Muqsit/ChestShop#63]
I really like this plugin, but it really disappointed me that all the categories I made have disappeared after I restarted my server.
Also, I would like to have an option to remove items from categories.

**Comment by MSG100TC** [comment]
It removed everything in my server after restart... Are you able to fix it?

**Comment by MSG100TC** [comment]
Please add a fix to it

**Comment by Muqsit** [comment]
Fixed in v5.0.0 https://poggit.pmmp.io/ci/Muqsit/ChestShop/ChestShop
