### ISSUE TITLE
help

### ISSUE THREAD

**Issue by TiesGamesNL** [Muqsit/ChestShop#7]
Notice: Trying to get property of non-object in C:\Users\Administrator\Downloads\PocketMine-MP - Copy (2)\plugins\ChestShop-c6c8acf20316859e2ae79a345f0e1f23d0f26b74\src\ChestShop\EventListener.php on line 70
[Tesseract] [19:00:49] CRITICAL> "Could not pass event 'pocketmine\event\inventory\InventoryTransactionEvent' to 'ChestShop v1.0.0': Call to a member function getValue() on null on ChestShop\EventListener
[Tesseract] [19:00:49] CRITICAL> Error: "Call to a member function getValue() on null" (EXCEPTION) in "/ChestShop-c6c8acf20316859e2ae79a345f0e1f23d0f26b74/src/ChestShop/EventListener" at line 70

**Comment by Muqsit** [comment]
Do not use spoons. This is only for PMMP.
