### ISSUE TITLE
Network issue cause some of players not access to shop

### ISSUE THREAD

**Issue by Adam1609** [Muqsit/ChestShop#75]
Some players in my server can open to another catergories, while others don't.

**Comment by Adam1609** [comment]
@Muqsit if you please check my issue, i will be appreciated

**Comment by Muqsit** [comment]
Are you using the latest 4.x version of this plugin?

**Comment by Muqsit** [comment]
Fixed in v5.0.0 https://poggit.pmmp.io/ci/Muqsit/ChestShop/ChestShop
