### ISSUE TITLE
Plugin Not Loading

### ISSUE THREAD

**Issue by CaptainHatchet** [Muqsit/ChestShop#79]
Me and another person used the .phar file from the poggit website, with economy api. We then restarted the server and the plugin wouldnt load. This also showed up, "Class 'poggit\libasynql\libasynql' not found" (EXCEPTION) in "plugins/ChestShop (1).phar/src/muqsit/chestshop/database/Database" at line 31.

**Comment by Muqsit** [comment]
Fixed in build 31, you can get it from: https://poggit.pmmp.io/ci/Muqsit/ChestShop/ChestShop
