### ISSUE TITLE
Not being able to buy picks when you put them in shop

### ISSUE THREAD

**Issue by XFizzer** [Muqsit/ChestShop#8]
14:37:38 [Server] Server thread/CRITICAL Error: "Call to a member function getValue() on null" (EXCEPTION) in "/ChestShop.phar/src/ChestShop/EventListener" at line 87
13.02 14:37:38 [Server] Server thread/CRITICAL "Could not pass event 'pocketmine\event\inventory\InventoryTransactionEvent' to 'ChestShop v1.0.0': Call to a member function getValue() on null on ChestShop\EventListener

**Comment by Muqsit** [comment]
Fixed https://github.com/Muqsit/ChestShop/commit/c4c895740dd6c24ae0bc1be194fd69c927a6f1ee
