### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by CaptainHatchet** [Muqsit/ChestShop#82]
When screen animations are on, you cant use shop. I would recommend increasing the threshold. Also if you buy an item when you dont have enough money for it, you still get the message saying you bought it.

**Comment by Muqsit** [comment]
@CaptainHatchet It works fine for me with and without screen animations. What it doesn't work fine with is when you use `./cs` instead of `/cs` which is a Bedrock Edition bug.

**Comment by CaptainHatchet** [comment]
I tried the latest version with screen animations. I cant open any category even if there is something in the category.
