### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by xorbs** [Muqsit/ChestShop#84]
How can I open category at once?

(ex)

(now)
/cs -> open Main UI

(I want to add)

/cs (categoryname) -> open category at once without MainUI

**Comment by Muqsit** [comment]
Is this a question or a feature suggestion?
If you want to write an add-on plugin:
```php
/** @var Loader $plugin */
/** @var Player $player */
$plugin->getChestShop()->getCategory("categoryname")->send($player);
```
