### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by PsychoPE** [Muqsit/ChestShop#85]
everything was working until i added these items to the shop, the UI opens but now when i open the ‘Blocks’ category nothing happens 
![673E0D91-5D6E-47BC-A590-461614E89876](https://user-images.githubusercontent.com/62428627/79307497-ea832180-7eee-11ea-9ef8-f9d8af6bcd40.jpeg)

**Comment by Adam1609** [comment]
Try turn off "screen animation" to see if it fix anything

**Comment by Muqsit** [comment]
Fixed by https://github.com/Muqsit/ChestShop/commit/d698e4c87e38fd73f12b31cb0e1e82133e99b7f8
