### ISSUE TITLE
Libasynql

### ISSUE THREAD

**Issue by VoltageMC** [Muqsit/ChestShop#86]
Undefined offset: 0 in phar:///home/container/plugins/ChestShop.phar/src/muqsit/chestshop/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php on line 120
Fatal error: Uncaught TypeError: Argument 2 passed to muqsit\chestshop\libs\poggit\libasynql\result\SqlColumnInfo::__construct() must be of the type string, null given, called in phar:///home/container/plugins/ChestShop.phar/src/muqsit/chestshop/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php on line 120 and defined in phar:///home/container/plugins/ChestShop.phar/src/muqsit/chestshop/libs/poggit/libasynql/result/SqlColumnInfo.php:37
--------------------------
This happens with PiggyAuctions sqlite file to, but can be fixed by using mysql. Please add mysql support ;-;

**Comment by Muqsit** [comment]
Please downgrade to PHP 7.3.15
