### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by Dapro718** [Muqsit/ChestShop#88]
80% of the time, when a player goes to open a category, the form closes and nothing happens. #

**Comment by Muqsit** [comment]
Can you send a recording? Works fine for me

**Comment by Dapro718** [comment]
Can’t send here. I’ll send it on discord

**Comment by Dapro718** [comment]
@Muqsit sorry for the late reply, here are the videos.
http://www.mediafire.com/folder/4xdvb2hdqrqriis,11by2sb9ckhxlya,dirspeq7d6ja8c1/shared

**Comment by Chronicoverride** [comment]
@Muqsit I am having the same issue as @Dapro718. Did you guys find a solution to this?

**Comment by Dapro718** [comment]
We did not. No reply from Muq. @Chronicoverride

**Comment by Chronicoverride** [comment]
Ok no prob. @Dapro718 I'm using PiggyShopUI plugin in place of chest shop and it appears to be working fine. May be worth a shot for you as well.

**Comment by Dapro718** [comment]
@Chronicoverride I dont like it, there is no back button which I like to have.

**Comment by Muqsit** [comment]
Possibly similar to #88
Is it possible for you to send me your .db file?

**Comment by Dapro718** [comment]
I do not have the file anymore. @Chronicoverride could you send it?

**Comment by Chronicoverride** [comment]
@Dapro718 Unfortunately I already uninstalled chest shop and installed and configured piggyshop. Sorry guys. If I go back for whatever reason and have the issue again I'll post.

**Comment by Muqsit** [comment]
Welp, gonna mark this as duplicate. Feel free to bump issue 85
