### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Mostro96** [Muqsit/ChestShop#90]
Notice: Undefined offset: 0 in phar:///root/Factions/plugins/ChestShop.phar/src/muqsit/
chestshop/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php on line 119                  
                                                                                       
Fatal error: Uncaught TypeError: Argument 2 passed to muqsit\chestshop\libs\poggit\liba
synql\result\SqlColumnInfo::__construct() must be of the type string, null given, calle
d in phar:///root/Factions/plugins/ChestShop.phar/src/muqsit/chestshop/libs/poggit/liba
synql/sqlite3/Sqlite3Thread.php on line 119 and defined in phar:///root/Factions/plugin
s/ChestShop.phar/src/muqsit/chestshop/libs/poggit/libasynql/result/SqlColumnInfo.php:37
Stack trace:                                                                           
#0 phar:///root/Factions/plugins/ChestShop.phar/src/muqsit/chestshop/libs/poggit/libasy
nql/sqlite3/Sqlite3Thread.php(119): muqsit\chestshop\libs\poggit\libasynql\result\SqlCo
lumnInfo->__construct('id', NULL)                                                      
#1 phar:///root/Factions/plugins/ChestShop.phar/src/muqsit/chestshop/libs/poggit/libasy
nql/base/SqlSlaveThread.php(77): muqsit\chestshop\libs\poggit\libasynql\sqlite3\Sqlite3
Thread->executeQuery(Object(SQLite3), 3, 'SELECT id, name...', Array)                  
#2 [internal function]: muqsit\chestshop\libs\poggit\libasynql\base\SqlSlaveThread->run
()                                                                                     
#3 {main}                                                                              
  thrown in phar:///root/Factions/plugins/ChestShop.phar/src/muqsit/chestshop/libs/pogg
it/libasynql/result/SqlColumnInfo.php on line 37``

**Comment by Muqsit** [comment]
Fixed by https://github.com/Muqsit/ChestShop/commit/d698e4c87e38fd73f12b31cb0e1e82133e99b7f8
