### ISSUE TITLE
BUG 1.16 POCKETMINE

### ISSUE THREAD

**Issue by fleximango** [Muqsit/ChestShop#92]
Hi, every time I try to open the chest shop with the command /cs or /cshop or /chestshop it just gives me internal error:

TamableSwing86 left the game
29.06 07:57:25 [Server] Server thread/INFO TamableSwing86[/83.86.74.103:58138] logged out due to client disconnect
29.06 07:58:05 [Disconnect] User TamableSwing86 has disconnected, reason: unknown

This is what it says on the console. Adding categories works and adding items works, just can’t open the shop.

**Comment by Muqsit** [comment]
@fleximango Please provide the error message along with the stack trace

**Comment by fleximango** [comment]
Where can I find the error message because on the console it just says that.
