### ISSUE TITLE
Category dont open 

### ISSUE THREAD

**Issue by AngelliaX** [Muqsit/ChestShop#98]
im using the chestshop.phar and the InvCrashFix_dev-3.phar

when i clicked a category which has item inside, it didnt open a new window, it just disappeared,no text displayed at all

"no related:" for each category, the window will close and open again, u may can make an update that only clear the previous item then add the new item so it will be much smoother

**Comment by Muqsit** [comment]
This would be related to InvMenu. There have been some slight improvements made in sending inventories since. Build #49 ([ChestShop_dev-49.phar](https://poggit.pmmp.io/r/161855/ChestShop_dev-49.phar)) should address it (it only supports PM4).
